### root access
GET http://localhost:8000

### Logon api endpoint
POST http://localhost:8000/api/v1/login
Content-Type:  application/json
   
{
    "email":"test@gmail.com",
    "password": "123454"
}

### category Zone ###
###fetch all category
GET  http://localhost:8000/api/v1/category


### Add a category

DELETE  http://localhost:8000/api/v1/category

### patch a category

PATCH  http://localhost:8000/api/v1/category
Content-Type:  application/json
   
{
    "name":"sanish",
   
   
}

### Product APIS
### Add new Product

POST http://localhost:8000/api/v1/product
Content-Type:  application/json
   
{
    "name":"Root  sanish",
    "price": 0
}


  