### root access
GET http://localhost:8000

### Lo
POST http://localhost:8000/api/v1/login
Content-Type:  application/json
   
{
     "email":"sanish23@gmail.com",
    "password": "123456"
}

### user router
### create a user
PUT  http://localhost:8000/api/v1/user
Content-Type:  application/json
   
{
  "fName":"sanish",
  "lName":"khadka",
    "email":"sanish213@gmail.com",
    "password": "123456",
    "role":"user"
}

### category Zone ###
###fetch all category

GET  http://localhost:8000/api/v1/category


### Add a category

DELETE  http://localhost:8000/api/v1/category

### patch a category

PATCH  http://localhost:8000/api/v1/category
Content-Type:  application/json
   
{
    "name":"sanish",
   
   
}

### Product APIS
### Add new Product

POST http://localhost:8000/api/v1/product
Content-Type:  application/json
   
{
    "name":"Root  sanish",
    "price": 0
}

### pitch for single product id update
  GET    http://localhost:8000/api/v1/product
  
   

### fetch for single product id update
  GET    http://localhost:8000/api/v1/product/607b9114e93a0f29f41d4cdc

   
### delete product
  DELETE http://localhost:8000/api/v1/localhost:8000/api/v1/products
Content-Type: application/json

{
  "_id": "607b9114e93a0f29f41d4cdc"
}