### root access
GET http://localhost:8000

### Lo
POST http://localhost:8000/api/v1/login
Content-Type:  application/json
   
{
     "email":"sanish31@gmail.com",
    "password": "123456"
}


###gt user by id
GET  http://localhost:8000/api/v1/user
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbmlzaDMxQGdtYWlsLmNvbSIsImlhdCI6MTYyMDIxMzkxNCwiZXhwIjoxNjIwMjE0ODE0fQ.thbRNUyhvZPF-oFyQq5qqoxWkzckBBQJXvJfKgus8BQ
### user router
### create a user
Post  http://localhost:8000/api/v1/user
Content-Type:  application/json
   
{
  "fName":"sanish",
  "lName":"khadka",
    "email":"sanish31@gmail.com",
    "password": "123456",
    "role":"user"
}

### category Zone ###
###fetch all category

GET  http://localhost:8000/api/v1/category


### Add a category

DELETE  http://localhost:8000/api/v1/category

### patch a category

PATCH  http://localhost:8000/api/v1/category
Content-Type:  application/json
   
{
    "name":"sanish",
   
   
}

### Product APIS
### Add new Product

POST http://localhost:8000/api/v1/product
Content-Type:  application/json
   
{
    "name":"Root  sanish",
    "price": 0
}

### pitch for single product id update
  GET    http://localhost:8000/api/v1/product
  
   

### fetch for single product id update
  GET    http://localhost:8000/api/v1/product/607b9114e93a0f29f41d4cdc

   
### delete product
  DELETE http://localhost:8000/api/v1/localhost:8000/api/v1/products
Content-Type: application/json

{
  "_id": "607b9114e93a0f29f41d4cdc"
}

### token endpoint
# Request fresh accessjwt
GET    http://localhost:8000/api/v1/token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbmlzaDMxQGdtYWlsLmNvbSIsImlhdCI6MTYyMDIxNDUzNywiZXhwIjoxNjIyODA2NTM3fQ.hFTZS5t-R5DqUxKBmeCbp9cS2cCHTSJq6ZECE-0Fv40